name: Tag with comment

on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo A comment on PR ${{ github.event.issue.number }}

      - name: Print PR info
        run: echo ${{ toJSON(github.event.issue.pull_request) }}
